### ISSUE TITLE
Issue that the "Download button couldn't be found!"

### ISSUE THREAD

**Issue by qianqli** [bioinf-mcb/gisaid-scrapper#24]
Dear there,

I have a problem when running the script. I run the script: "python3 scrap.py -u ààà -p àààà -w", and got the error message about 30min later.

Traceback (most recent call last):
  File "scrap.py", line 79, in <module>
    scrapper.download_packages('metadata_tsv')
  File "/Users/qianqian/gisaid-scrapper/gisaid_scrapper.py", line 278, in download_packages
    assert download is not None, "Download button couldn't be found!"
AssertionError: Download button couldn't be found!

Could you help to give some solution? 

Thanks
Qianqian

**Comment by qianqli** [comment]
Dear there,

I found out the problem:  for some GISAID registers, the download packages are not available. You need to apply to access this part of the function. 

Qianqian
