### ISSUE TITLE
Error message: selenium.common.exceptions.ElementClickInterceptedException: Message: Element <td class="yui-dt0-col-d yui-dt-col-d yui-dt-sortable yui-dt-resizeable"> is not clickable at point (x,y) because another element <div class="yui-dt-bd"> obscures it

### ISSUE THREAD

**Issue by chwisteeng** [bioinf-mcb/gisaid-scrapper#3]
Hi, I keep getting this error message when trying to download the fasta files with both your original script and this updated one. I see in the updated script that it includes a scrolling function, but I'm still running into issues with the program not being able to continue because it following file isn't visible. Can you assist? Thank you!

**Comment by chwisteeng** [comment]
Or I eventually run into out of bounds errors.

Traceback (most recent call last):
  File "scrap.py", line 59, in <module>
    scrapper.download_from_curr_page()
  File ".../gisaid-scrapper-master/gisaid_scrapper.py", line 139, in download_from_curr_page
    self._download_row(parent_form, i)
  File ".../gisaid-scrapper-master/gisaid_scrapper.py", line 154, in _download_row
    self._action_click(self.driver.find_elements_by_tag_name("button")[1])
IndexError: list index out of range

**Comment by wwydmanski** [comment]
Does it happen in regular or headless mode?

**Comment by chwisteeng** [comment]
This happens in regular mode

**Comment by majkiw** [comment]
For me this was caused by a scrollbar over the last row.
Using bigger monitor helped!

**Comment by majkiw** [comment]
(decreasing font size with `Ctrl/Cmd` + `-` in a running window until vertical scrollbar dissappears also works)

**Comment by chwisteeng** [comment]
Oh cool! Thank you @majkiw :) I appreciate it!
